FROM golang:1.14.2-alpine

RUN apk update && apk add --no-cache git

RUN mkdir -p /usr/schedulo/
WORKDIR /usr/schedulo/

COPY . .

CMD GOMOD111=on CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go test --cover -v github.com/yanishoss/schedulo/cmd/schedulo_server