name: Docker Image LATEST

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}
      - name: Run unit tests
        id: go_test_unit
        run: cd test && chmod +x ./run.sh && ./run.sh
      - name: Run integration tests
        id: go_test_integration
        run: cd integration && chmod +x ./run.sh && ./run.sh
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.ref}}
    - name: Build the Docker image
      run: docker build . --file cmd/schedulo_server/Dockerfile --tag germainion/schedulo:latest && docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} && docker push germainion/schedulo:latest
      needs: test